Gb edf metadata adapter
mlexchange/workflow-viz pull request #2
Opened 2024-12-04 16:02 UTC by rajasriramoju

This branch deals with the adapter for .gb files. Additional functionality has been added for .gb file ingestion. The goal is to take metadata associated with the .edf images associated to the respective sfloat .gb image: the hi and lo  .edf images. The helper function create new indices if the same key exists with different values in the hi and low images' metadata, in order to not lose information. 

The current version works in ingesting .gb files when there are .edf files with the associated .txt files. But there is a bug when ingesting a folder with just .gb files. This adapter needs debugging. The current terminal output looks like this:

<img width="1045" alt="Screenshot 2024-12-04 at 8 01 41 PM" src="https://github.com/user-attachments/assets/bf5df9fc-98aa-4a53-987c-9d31077225b3">

with a final error statement of: ```AttributeError: 'NoneType' object has no attribute 'new'```

2025-01-17 19:26 UTC, Wiebke requested changes
Overall looks great.

I left a few very minor comments, the one regarding date comparison is likely of more relevance for the similar if a simple sort mechanism on strings is in use there currently.

2025-01-17 19:26 UTC, Wiebke commented on tiled/config/custom/gb.py
> +        gb_dictionary["Date"] = hi_date if hi_date > lo_date else lo_date
At this point, both `hi_date` and `lo_date` should be of type `string`. Given that the format in the header is of form e.g. `Sat Apr  1 11:35:48 2023` this may be lead to incorrect ordering if high and low scan happen to involve a date switch.

This is unlikely to matter much here, but would be important to take into account in e.g. sorting according to date.

2025-01-17 19:26 UTC, Wiebke commented on tiled/config/custom/gb.py
> +        lo_date = lo_header.get("Date")
Any particular reason why the remainder of the header information is not added to the metadata?

2025-01-17 19:26 UTC, Wiebke commented on tiled/config/custom/gb.py
> +    # returned in the parse_txt_accompanying_edf method
This seems to be a slightly outdated comment.

2025-01-17 23:56 UTC, rajasriramoju commented on tiled/config/custom/gb.py
> +    # returned in the parse_txt_accompanying_edf method
The comment isn't outdated, but it will be written better to explain why an empty dictionary is needed.

2025-01-17 23:58 UTC, rajasriramoju commented on tiled/config/custom/gb.py
> +        lo_date = lo_header.get("Date")
The header information will now be added to the metadata dictionary. Previously, only the date was required from the header, but the header data will not be added to avoid loss of any information.

2025-02-14 22:57 UTC, rajasriramoju commented on tiled/config/custom/gb.py
> +        gb_dictionary["Date"] = hi_date if hi_date > lo_date else lo_date
The latest commit now addresses this, and compares the two dates as datetime objects 👍🏼

2025-03-12 15:41 UTC, Wiebke approved these changes
Nice work!

One aspect that remains to be investigated in regards to the adapters is why gb adapter is called multiple times: If a corresponding `.edf` does not exist for a `.gb` file, the warning regarding this gets logged three times. 

Testing and attempting to debug #10, indicates that this is not related to this adapter in particular, but would be good to understand overall.

2025-03-12 15:41 UTC, merged